url: https://update.airvlc.com
file_host: https://download.airvlc.com
title: AirVLC Release Notes
description: This feed contains application updates for AirVLC.
google_analytics: UA-27275793-10 # Definitely change this
lang: en
exclude: ["Rakefile", "glow.rb", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "_config-sample.yml"]
include: ["_redirects"]
destination: "_site" # Remember to change this value in the Rakefile as well
permalink: /:title

# Glow settings
download_path: "_site/download" # Don't add a trailing /
binary_path: ".." # Don't add a trailing /
beta_indicator: b # Should appear after the short version number: 0.3b
require_signing: true # Should the app be signed using a private key
